version: "3.8"

services:

  traefik:
    image: "traefik:v2.5.2"
    container_name: "traefik"
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=a.cattermole@newcastle.ac.uk"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - "traefik_default"

  mysql:
    restart: always
    image: mysql/mysql-server:8.0
    container_name: mlflow_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mlflow
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - A

  mlflow:
    image: mlflow
    container_name: mlflow
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - A
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mlflow.rule=Host(`$MLFLOW_TRACKING_HOSTNAME`)"
      - "traefik.http.routers.mlflow.entrypoints=websecure"
      - "traefik.http.routers.mlflow.tls.certresolver=myresolver"
      - "traefik.http.middlewares.mlflow-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.mlflow-redirectscheme.redirectscheme.permanent=true"
      - traefik.http.routers.mlflow.middlewares=mlflow-redirectscheme@docker,mlflow-basicauth@docker
      - traefik.docker.network=mlflow-docker-azure_traefik_default
      - "traefik.http.middlewares.mlflow-basicauth.basicauth.users=$MLFLOW_TRACKING_USERNAME:$MLFLOW_TRACKING_PASSWORD_HASH"
    entrypoint: >
        wait-for-it traefik:443 -t 90 --
        wait-for-it mysql:3306 -t 180 --
        mlflow server
        --backend-store-uri mysql://$MYSQL_USER:$MYSQL_PASSWORD@mysql:3306/mlflow
        --default-artifact-root wasbs://$AZURE_STORAGE_CONTAINER@$AZURE_STORAGE_ACCOUNT.blob.core.windows.net
        -h 0.0.0.0

networks:
  traefik_default:
    driver: bridge
  A:
    driver: bridge
